---

    # sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

- name: Run Rancher Server
  docker_container:
    name: rancher-server
    image: rancher/rancher
    state: started
    restart: yes
    ports:
    - "80:80"
    - "443:443"
    
