---

#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest

#- name: Check for reboot hint.
#  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
#  ignore_errors: true
#  register: reboot_hint

#- name: Reboot a slow machine that might have lots of updates to apply
#  reboot:
#    reboot_timeout: 3600
#  when: reboot_hint.stdout.find("reboot") != -1

- name: Install ssg
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - openscap-scanner
    - scap-security-guide

- name: Perform oscap scan 
  command: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
  ignore_errors: yes

- name: Store scan report to ansible server results directory
  fetch:
    src: report.html
    dest: ./results/{{ inventory_hostname }}/oscap-report-{{ansible_date_time.date}}-{{ansible_date_time.time}}.html
    flat: yes

- name: Store scan arf to ansible server results directory
  fetch:
    src: arf.xml
    dest: ./results/{{ inventory_hostname }}/oscap-arf-{{ansible_date_time.date}}-{{ansible_date_time.time}}.xml
    flat: yes
